# Generated by Django 3.2.6 on 2021-08-25 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('features', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audio_store',
            name='record',
            field=models.FileField(upload_to=''),
        ),
        migrations.AlterModelTable(
            name='audio_store',
            table=None,
        ),
    ]
