# Generated by Django 3.2.6 on 2021-08-25 11:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('features', '0002_auto_20210825_1631'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='audio_store',
            table='Audio_store',
        ),
    ]
