# Generated by Django 3.2.6 on 2021-08-25 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('features', '0004_alter_audio_store_record'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSong',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audio_file', models.FileField(upload_to='documents/')),
            ],
        ),
        migrations.DeleteModel(
            name='Audio_store',
        ),
    ]
